name: WeeSmartVN CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the site
      run: |
        ls -la
        pwd
        rm -rf /var/www/wee/*
        cp -R $(pwd)/* /var/www/wee
        echo visit: https://weesmartvn.com
    - name: Clear Cache
      run: |
        curl --location --request POST 'https://api.cloudflare.com/client/v4/zones/efcb1cef31433992425cacfbfb245460/purge_cache' \
            --header 'Content-Type: application/json' \
            --header 'X-Auth-Email: rexviet@gmail.com' \
            --header 'X-Auth-Key: 7c4763ac9c1bf24ed463be0cc6c82f8e97fb9' \
            --header 'Cookie: __cflb=0H28vgHxwvgAQtjUGU56Rb8iNWZVUvXhtmhFGrTeSNy; __cfruid=1b043d41af712ef47329eaac5b0d6541816adcff-1670738508' \
            --data-raw '{
              "files": [
                "https://weesmartvn.com/*",
                "https://weesmartvn.com/index.html",
                "https://weesmartvn.com/style/*.css",
                "https://weesmartvn.com/script.js"
              ]
            }'
